language: node_js
node_js:
  - '0.10'
  - '0.8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-flask' ]; then cd .. && eval "mv $currentfolder generator-angular-flask" && cd generator-angular-flask; fi

